# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.9
_src_path: gh:FallingColors/hexdummy
author: M1tht1c
capitalize_platforms: false
classname: Hex_wards
default_branch: main
description: Hex_wards addon for Hex Casting
display_name: Hex_wards
github_repo: hex_wards
hexcasting_version: 0.10.3
homepage_url: https://m1tht1c.github.io/hex_wards
initial_mod_version: 0.0.1
java_version: 17
license: MIT
mappings_name: Mojmap
modid: hex_wards
package: net.hex_wards
sources_url: https://github.com/M1tht1c/hex_wards
