modid = "hex_wards"
book = "hex_wards:hex_wardsbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
]
export_dir = "src/hexdoc_hex_wards/_export/generated"

[template]
icon = "icon.png"
include = [
    "hex_wards",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hex_wards"
author = "M1tht1c"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
_pattern_regex = { "!Raw"='(?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?' }
_per_world_value = "registerPerWorld"

[[extra.hexcasting.pattern_stubs]]
path = "{^^^_common.package}/registry/Hex_wardsPatternRegistry.java"
regex = "{^_pattern_regex}"
per_world_value = "{^_per_world_value}"

# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/net/hex_wards"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/net/hex_wards/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/net/hex_wards/forge"
